<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-181TTAT" failures="4" tests="36" name="Test_All_Modules_firefox" time="358.019" errors="0" timestamp="2025-08-15T10:14:30 GMT-04:00">
  <testcase classname="testCases.Stack" name="open_stac_page" time="0.453"/>
  <testcase classname="testCases.Queue" name="open_queue_page" time="0.546"/>
  <testcase classname="testCases.Stack" name="stackOperations" time="1.257"/>
  <testcase classname="testCases.Queue" name="queueImplementation" time="1.191"/>
  <testcase classname="testCases.Stack" name="stackoperationsCodeEditor" time="1.93"/>
  <testcase classname="testCases.Queue" name="queueImplementationCodeEditor" time="2.351"/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="2.73">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="2.839">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="2.821">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="3.347">
    <failure type="java.lang.AssertionError" message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at testCases.Stack.StackTryingEmptyEditor(Stack.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- StackTryingEmptyEditor -->
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="3.139">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="2.838">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="3.085">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="2.105">
    <failure type="java.lang.AssertionError" message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at testCases.Queue.queueTryingEmptyEditor(Queue.java:71)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- queueTryingEmptyEditor -->
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="1.744"/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="1.112"/>
  <testcase classname="testCases.Queue" name="queueTryingValidAndInvalidCode" time="0.958"/>
  <testcase classname="testCases.Queue" name="queueTryingValidAndInvalidCode" time="0.979"/>
  <testcase classname="testCases.Stack" name="stackimplementation" time="0.401"/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingCollection" time="0.388"/>
  <testcase classname="testCases.Stack" name="stackimplementationCodeEditor" time="1.082"/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingCollectionCodeEditor" time="0.814"/>
  <testcase classname="testCases.Stack" name="stackapplication" time="0.402"/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingArray" time="0.397"/>
  <testcase classname="testCases.Stack" name="stackapplicationCodeEditor" time="0.834"/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingArrayCodeEditor" time="0.8"/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="0.62">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="0.562">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="0.636">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="0.555">
    <failure type="java.lang.AssertionError" message="Failing this test case to show the bug which is,there are no practice questions available for stack module">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for stack module
at testCases.Stack.StackopenPracticeQuestions(Stack.java:148)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- StackopenPracticeQuestions -->
  <testcase classname="testCases.Queue" name="queueOperations" time="0.417"/>
  <testcase classname="testCases.Queue" name="queueOperationsCodeEditor" time="0.829"/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="0.618">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="0.655">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="0.57">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="0.545">
    <failure type="java.lang.AssertionError" message="Failing this test case to show the bug which is,there are no practice questions available for queue module">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for queue module
at testCases.Queue.queueOpenPracticeQuestions(Queue.java:170)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- queueOpenPracticeQuestions -->
</testsuite> <!-- Test_All_Modules_firefox -->
