<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Yuvaraj" failures="2" tests="12" name="Test_All_Modules_edge" time="88.684" errors="0" timestamp="2025-08-16T06:47:33 EDT">
  <testcase classname="testCases.GraphTest" name="getClick_Graph" time="1.421"/>
  <testcase classname="testCases.GraphTest" name="getClick_GraphRepre" time="0.954"/>
  <testcase classname="testCases.GraphTest" name="graphTryingValidAndInvalidCode" time="1.814"/>
  <testcase classname="testCases.GraphTest" name="graphTryingValidAndInvalidCode" time="1.918"/>
  <testcase classname="testCases.GraphTest" name="runWithoutCode" time="2.126">
    <skipped/>
  </testcase> <!-- runWithoutCode -->
  <testcase classname="testCases.GraphTest" name="runWithoutCode" time="1.887">
    <skipped/>
  </testcase> <!-- runWithoutCode -->
  <testcase classname="testCases.GraphTest" name="runWithoutCode" time="1.84">
    <skipped/>
  </testcase> <!-- runWithoutCode -->
  <testcase classname="testCases.GraphTest" name="runWithoutCode" time="2.069">
    <failure type="java.lang.AssertionError" message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at testCases.GraphTest.runWithoutCode(GraphTest.java:93)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- runWithoutCode -->
  <testcase classname="testCases.GraphTest" name="practQuestion" time="1.989">
    <skipped/>
  </testcase> <!-- practQuestion -->
  <testcase classname="testCases.GraphTest" name="practQuestion" time="1.526">
    <skipped/>
  </testcase> <!-- practQuestion -->
  <testcase classname="testCases.GraphTest" name="practQuestion" time="1.684">
    <skipped/>
  </testcase> <!-- practQuestion -->
  <testcase classname="testCases.GraphTest" name="practQuestion" time="1.323">
    <failure type="java.lang.AssertionError" message="Practice Question is blank and failed the testcases to show the bug">
      <![CDATA[java.lang.AssertionError: Practice Question is blank and failed the testcases to show the bug
at testCases.GraphTest.practQuestion(GraphTest.java:105)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- practQuestion -->
</testsuite> <!-- Test_All_Modules_edge -->
