<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-181TTAT" failures="4" tests="36" name="Test_All_Modules_edge" time="217.217" errors="0" timestamp="2025-08-17T00:37:44 GMT-04:00">
  <testcase classname="testCases.StackTest" name="open_stac_page" time="0.408"/>
  <testcase classname="testCases.QueueTest" name="open_queue_page" time="0.537"/>
  <testcase classname="testCases.StackTest" name="stackOperations" time="1.242"/>
  <testcase classname="testCases.QueueTest" name="queueImplementation" time="0.933"/>
  <testcase classname="testCases.StackTest" name="stackoperationsCodeEditor" time="2.171"/>
  <testcase classname="testCases.QueueTest" name="queueImplementationCodeEditor" time="1.515"/>
  <testcase classname="testCases.StackTest" name="StackTryingEmptyEditor" time="2.045">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <testcase classname="testCases.StackTest" name="StackTryingEmptyEditor" time="2.155">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <testcase classname="testCases.StackTest" name="StackTryingEmptyEditor" time="2.011">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <testcase classname="testCases.StackTest" name="StackTryingEmptyEditor" time="2.517">
    <failure type="java.lang.AssertionError" message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at testCases.StackTest.StackTryingEmptyEditor(StackTest.java:78)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- StackTryingEmptyEditor -->
  <testcase classname="testCases.QueueTest" name="queueTryingEmptyEditor" time="2.175">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <testcase classname="testCases.QueueTest" name="queueTryingEmptyEditor" time="1.859">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <testcase classname="testCases.QueueTest" name="queueTryingEmptyEditor" time="2.378">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <testcase classname="testCases.QueueTest" name="queueTryingEmptyEditor" time="1.713">
    <failure type="java.lang.AssertionError" message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at testCases.QueueTest.queueTryingEmptyEditor(QueueTest.java:80)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- queueTryingEmptyEditor -->
  <testcase classname="testCases.StackTest" name="StackTryingValidAndInvalidCode" time="2.297"/>
  <testcase classname="testCases.StackTest" name="StackTryingValidAndInvalidCode" time="1.668"/>
  <testcase classname="testCases.QueueTest" name="queueTryingValidAndInvalidCode" time="2.217"/>
  <testcase classname="testCases.QueueTest" name="queueTryingValidAndInvalidCode" time="1.656"/>
  <testcase classname="testCases.StackTest" name="stackimplementation" time="1.154"/>
  <testcase classname="testCases.QueueTest" name="queueImplementationUsingCollection" time="0.843"/>
  <testcase classname="testCases.StackTest" name="stackimplementationCodeEditor" time="1.723"/>
  <testcase classname="testCases.QueueTest" name="queueImplementationUsingCollectionCodeEditor" time="1.58"/>
  <testcase classname="testCases.StackTest" name="stackapplication" time="0.852"/>
  <testcase classname="testCases.QueueTest" name="queueImplementationUsingArray" time="1.021"/>
  <testcase classname="testCases.StackTest" name="stackapplicationCodeEditor" time="1.731"/>
  <testcase classname="testCases.QueueTest" name="queueImplementationUsingArrayCodeEditor" time="2.558"/>
  <testcase classname="testCases.StackTest" name="StackopenPracticeQuestions" time="1.625">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <testcase classname="testCases.StackTest" name="StackopenPracticeQuestions" time="2.04">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <testcase classname="testCases.StackTest" name="StackopenPracticeQuestions" time="1.803">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <testcase classname="testCases.StackTest" name="StackopenPracticeQuestions" time="1.624">
    <failure type="java.lang.AssertionError" message="Failing this test case to show the bug which is,there are no practice questions available for stack module">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for stack module
at testCases.StackTest.StackopenPracticeQuestions(StackTest.java:160)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- StackopenPracticeQuestions -->
  <testcase classname="testCases.QueueTest" name="queueOperations" time="1.659"/>
  <testcase classname="testCases.QueueTest" name="queueOperationsCodeEditor" time="1.598"/>
  <testcase classname="testCases.QueueTest" name="queueOpenPracticeQuestions" time="2.046">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <testcase classname="testCases.QueueTest" name="queueOpenPracticeQuestions" time="1.558">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <testcase classname="testCases.QueueTest" name="queueOpenPracticeQuestions" time="2.091">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <testcase classname="testCases.QueueTest" name="queueOpenPracticeQuestions" time="1.809">
    <failure type="java.lang.AssertionError" message="Failing this test case to show the bug which is,there are no practice questions available for queue module">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for queue module
at testCases.QueueTest.queueOpenPracticeQuestions(QueueTest.java:181)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- queueOpenPracticeQuestions -->
</testsuite> <!-- Test_All_Modules_edge -->
