<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-181TTAT" failures="4" tests="36" name="Test_All_Modules_chrome" time="256.209" errors="0" timestamp="2025-08-17T00:09:24 GMT-04:00">
  <testcase classname="testCases.Stack" name="open_stac_page" time="0.849"/>
  <testcase classname="testCases.Queue" name="open_queue_page" time="0.594"/>
  <testcase classname="testCases.Stack" name="stackOperations" time="1.395"/>
  <testcase classname="testCases.Queue" name="queueImplementation" time="1.296"/>
  <testcase classname="testCases.Stack" name="stackoperationsCodeEditor" time="2.136"/>
  <testcase classname="testCases.Queue" name="queueImplementationCodeEditor" time="1.785"/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="2.593">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="1.934">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="2.768">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="2.129">
    <failure type="java.lang.AssertionError" message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at testCases.Stack.StackTryingEmptyEditor(Stack.java:78)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- StackTryingEmptyEditor -->
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="2.33">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="1.984">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="2.084">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="2.381">
    <failure type="java.lang.AssertionError" message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at testCases.Queue.queueTryingEmptyEditor(Queue.java:80)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- queueTryingEmptyEditor -->
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="2.118"/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="2.316"/>
  <testcase classname="testCases.Queue" name="queueTryingValidAndInvalidCode" time="2.646"/>
  <testcase classname="testCases.Queue" name="queueTryingValidAndInvalidCode" time="2.419"/>
  <testcase classname="testCases.Stack" name="stackimplementation" time="1.349"/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingCollection" time="1.02"/>
  <testcase classname="testCases.Stack" name="stackimplementationCodeEditor" time="2.085"/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingCollectionCodeEditor" time="1.675"/>
  <testcase classname="testCases.Stack" name="stackapplication" time="1.595"/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingArray" time="1.539"/>
  <testcase classname="testCases.Stack" name="stackapplicationCodeEditor" time="1.497"/>
  <testcase classname="testCases.Queue" name="queueImplementationUsingArrayCodeEditor" time="2.206"/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="1.418">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="2.041">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="1.491">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="1.664">
    <failure type="java.lang.AssertionError" message="Failing this test case to show the bug which is,there are no practice questions available for stack module">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for stack module
at testCases.Stack.StackopenPracticeQuestions(Stack.java:160)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- StackopenPracticeQuestions -->
  <testcase classname="testCases.Queue" name="queueOperations" time="1.459"/>
  <testcase classname="testCases.Queue" name="queueOperationsCodeEditor" time="1.891"/>
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="1.396">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="1.637">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="1.692">
    <skipped/>
  </testcase> <!-- queueOpenPracticeQuestions -->
  <testcase classname="testCases.Queue" name="queueOpenPracticeQuestions" time="1.401">
    <failure type="java.lang.AssertionError" message="Failing this test case to show the bug which is,there are no practice questions available for queue module">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for queue module
at testCases.Queue.queueOpenPracticeQuestions(Queue.java:181)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- queueOpenPracticeQuestions -->
</testsuite> <!-- Test_All_Modules_chrome -->
