<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-181TTAT" failures="3" tests="27" name="testCases.Queue" time="175.439" errors="0" timestamp="2025-08-14T17:31:39 GMT-04:00" skipped="9">
  <testcase classname="testCases.Queue" name="open_queue_page" time="4.976"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="open_queue_page" time="4.359"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="open_queue_page" time="6.082"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementation" time="5.177"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementation" time="4.831"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementation" time="5.711"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationCodeEditor" time="5.596"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationCodeEditor" time="4.932"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueImplementationCodeEditor" time="11.409"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="5.144">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="6.143">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="10.879">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.Queue.queueTryingEmptyEditor(Queue.java:71)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="5.346">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="6.244">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="6.237">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="6.002">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.Queue.queueTryingEmptyEditor(Queue.java:71)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="8.410">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="5.570">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="6.179">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="6.468">
    <skipped/>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingEmptyEditor" time="5.835">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.Queue.queueTryingEmptyEditor(Queue.java:71)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- queueTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingValidAndInvalidCode" time="5.301"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingValidAndInvalidCode" time="5.589"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingValidAndInvalidCode" time="5.378"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingValidAndInvalidCode" time="10.041"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingValidAndInvalidCode" time="11.045"/>
  <system-out/>
  <testcase classname="testCases.Queue" name="queueTryingValidAndInvalidCode" time="6.555"/>
  <system-out/>
</testsuite> <!-- testCases.Queue -->
