<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-181TTAT" failures="3" tests="42" name="testCases.Stack" time="269.326" errors="0" timestamp="2025-08-14T23:56:24 GMT-04:00" skipped="9">
  <testcase classname="testCases.Stack" name="open_stac_page" time="4.587"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="open_stac_page" time="9.617"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="open_stac_page" time="4.933"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackOperations" time="5.322"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackOperations" time="5.917"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackOperations" time="5.029"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackoperationsCodeEditor" time="12.301"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackoperationsCodeEditor" time="5.322"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackoperationsCodeEditor" time="4.900"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="5.499">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="5.200">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="10.887">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="4.614">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.Stack.StackTryingEmptyEditor(Stack.java:72)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="6.195">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="5.350">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="5.067">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="5.513">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="6.861">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.Stack.StackTryingEmptyEditor(Stack.java:72)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="8.082">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="6.719">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="5.137">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.Stack.StackTryingEmptyEditor(Stack.java:72)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="6.102"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="11.084"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="6.125"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="5.467"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="5.064"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="7.610"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackimplementation" time="5.458"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackimplementation" time="5.071"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackimplementation" time="4.957"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackimplementationCodeEditor" time="5.564"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackimplementationCodeEditor" time="11.022"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackimplementationCodeEditor" time="5.897"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackapplication" time="4.351"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackapplication" time="4.771"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackapplication" time="10.930"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackapplicationCodeEditor" time="9.741"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackapplicationCodeEditor" time="5.296"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackapplicationCodeEditor" time="5.285"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="4.835"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="5.496"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="6.148"/>
  <system-out/>
</testsuite> <!-- testCases.Stack -->
